export default {
  blush: [
    { key: `Canadian`, value: `Canadian`, text: `Canadian` },
    { key: `EWG_Verified`, value: `EWG Verified`, text: `Ewg verified` },
    { key: `CertClean`, value: `CertClean`, text: `Certclean` },
    { key: `Gluten_Free`, value: `Gluten Free`, text: `Gluten free` },
    { key: `Hypoallergenic`, value: `Hypoallergenic`, text: `Hypoallergenic` },
    { key: `Natural`, value: `Natural`, text: `Natural` },
    { key: `No_Talc`, value: `No Talc`, text: `No talc` },
    { key: `Non-GMO`, value: `Non-GMO`, text: `Non-gmo` },
    { key: `Organic`, value: `Organic`, text: `Organic` },
    { key: `purpicks`, value: `purpicks`, text: `Purpicks` },
    { key: `USDA_Organic`, value: `USDA Organic`, text: `Usda organic` },
    { key: `Vegan`, value: `Vegan`, text: `Vegan` },
  ],
  bronzer: [
    { key: `Canadian`, value: `Canadian`, text: `Canadian` },
    { key: `EWG_Verified`, value: `EWG Verified`, text: `Ewg verified` },
    { key: `Gluten_Free`, value: `Gluten Free`, text: `Gluten free` },
    { key: `Natural`, value: `Natural`, text: `Natural` },
    { key: `Organic`, value: `Organic`, text: `Organic` },
    { key: `purpicks`, value: `purpicks`, text: `Purpicks` },
    { key: `Vegan`, value: `Vegan`, text: `Vegan` },
  ],
  eyebrow: [
    { key: `EWG_Verified`, value: `EWG Verified`, text: `Ewg verified` },
    { key: `purpicks`, value: `purpicks`, text: `Purpicks` },
  ],
  eyeliner: [
    { key: `Canadian`, value: `Canadian`, text: `Canadian` },
    { key: `EcoCert`, value: `EcoCert`, text: `Ecocert` },
    { key: `EWG_Verified`, value: `EWG Verified`, text: `Ewg verified` },
    { key: `CertClean`, value: `CertClean`, text: `Certclean` },
    { key: `Gluten_Free`, value: `Gluten Free`, text: `Gluten free` },
    { key: `Hypoallergenic`, value: `Hypoallergenic`, text: `Hypoallergenic` },
    { key: `Natural`, value: `Natural`, text: `Natural` },
    { key: `No_Talc`, value: `No Talc`, text: `No talc` },
    { key: `Organic`, value: `Organic`, text: `Organic` },
    { key: `purpicks`, value: `purpicks`, text: `Purpicks` },
    { key: `Vegan`, value: `Vegan`, text: `Vegan` },
  ],
  eyeshadow: [
    { key: `Canadian`, value: `Canadian`, text: `Canadian` },
    { key: `EcoCert`, value: `EcoCert`, text: `Ecocert` },
    { key: `EWG_Verified`, value: `EWG Verified`, text: `Ewg verified` },
    { key: `CertClean`, value: `CertClean`, text: `Certclean` },
    { key: `Gluten_Free`, value: `Gluten Free`, text: `Gluten free` },
    { key: `Hypoallergenic`, value: `Hypoallergenic`, text: `Hypoallergenic` },
    { key: `Natural`, value: `Natural`, text: `Natural` },
    { key: `No_Talc`, value: `No Talc`, text: `No talc` },
    { key: `Non-GMO`, value: `Non-GMO`, text: `Non-gmo` },
    { key: `Organic`, value: `Organic`, text: `Organic` },
    { key: `purpicks`, value: `purpicks`, text: `Purpicks` },
    { key: `USDA_Organic`, value: `USDA Organic`, text: `Usda organic` },
    { key: `Vegan`, value: `Vegan`, text: `Vegan` },
  ],
  foundation: [
    { key: `Canadian`, value: `Canadian`, text: `Canadian` },
    { key: `CertClean`, value: `CertClean`, text: `Certclean` },
    { key: `EWG_Verified`, value: `EWG Verified`, text: `Ewg verified` },
    { key: `Gluten_Free`, value: `Gluten Free`, text: `Gluten free` },
    { key: `Hypoallergenic`, value: `Hypoallergenic`, text: `Hypoallergenic` },
    { key: `Natural`, value: `Natural`, text: `Natural` },
    { key: `No_Talc`, value: `No Talc`, text: `No talc` },
    { key: `Vegan`, value: `Vegan`, text: `Vegan` },
    { key: `alcohol_free`, value: `alcohol free`, text: `Alcohol free` },
    { key: `cruelty_free`, value: `cruelty free`, text: `Cruelty free` },
    { key: `oil_free`, value: `oil free`, text: `Oil free` },
    { key: `purpicks`, value: `purpicks`, text: `Purpicks` },
    { key: `silicone_free`, value: `silicone free`, text: `Silicone free` },
    { key: `water_free`, value: `water free`, text: `Water free` },
  ],
  lip_liner: [
    { key: `Canadian`, value: `Canadian`, text: `Canadian` },
    { key: `EWG_Verified`, value: `EWG Verified`, text: `Ewg verified` },
    { key: `Gluten_Free`, value: `Gluten Free`, text: `Gluten free` },
    { key: `Hypoallergenic`, value: `Hypoallergenic`, text: `Hypoallergenic` },
    { key: `Natural`, value: `Natural`, text: `Natural` },
    { key: `No_Talc`, value: `No Talc`, text: `No talc` },
    { key: `Vegan`, value: `Vegan`, text: `Vegan` },
    { key: `cruelty_free`, value: `cruelty free`, text: `Cruelty free` },
    { key: `purpicks`, value: `purpicks`, text: `Purpicks` },
  ],
  lipstick: [
    { key: `Canadian`, value: `Canadian`, text: `Canadian` },
    { key: `CertClean`, value: `CertClean`, text: `Certclean` },
    { key: `Chemical_Free`, value: `Chemical Free`, text: `Chemical free` },
    { key: `EWG_Verified`, value: `EWG Verified`, text: `Ewg verified` },
    { key: `Gluten_Free`, value: `Gluten Free`, text: `Gluten free` },
    { key: `Hypoallergenic`, value: `Hypoallergenic`, text: `Hypoallergenic` },
    { key: `Natural`, value: `Natural`, text: `Natural` },
    { key: `No_Talc`, value: `No Talc`, text: `No talc` },
    { key: `Non-GMO`, value: `Non-GMO`, text: `Non-gmo` },
    { key: `Organic`, value: `Organic`, text: `Organic` },
    { key: `Peanut_Free_Product`, value: `Peanut Free Product`, text: `Peanut free product` },
    { key: `Vegan`, value: `Vegan`, text: `Vegan` },
    { key: `cruelty_free`, value: `cruelty free`, text: `Cruelty free` },
    { key: `purpicks`, value: `purpicks`, text: `Purpicks` },
  ],
  mascara: [
    { key: `Canadian`, value: `Canadian`, text: `Canadian` },
    { key: `CertClean`, value: `CertClean`, text: `Certclean` },
    { key: `EWG_Verified`, value: `EWG Verified`, text: `Ewg verified` },
    { key: `EcoCert`, value: `EcoCert`, text: `Ecocert` },
    { key: `Gluten_Free`, value: `Gluten Free`, text: `Gluten free` },
    { key: `Hypoallergenic`, value: `Hypoallergenic`, text: `Hypoallergenic` },
    { key: `No_Talc`, value: `No Talc`, text: `No talc` },
    { key: `Organic`, value: `Organic`, text: `Organic` },
    { key: `USDA_Organic`, value: `USDA Organic`, text: `Usda organic` },
    { key: `purpicks`, value: `purpicks`, text: `Purpicks` },
  ],
  nail_polish: [
    { key: `Canadian`, value: `Canadian`, text: `Canadian` },
    { key: `Fair_Trade`, value: `Fair Trade`, text: `Fair trade` },
    { key: `Gluten_Free`, value: `Gluten Free`, text: `Gluten free` },
    { key: `Natural`, value: `Natural`, text: `Natural` },
    { key: `Non-GMO`, value: `Non-GMO`, text: `Non-gmo` },
    { key: `Sugar_Free`, value: `Sugar Free`, text: `Sugar free` },
    { key: `Vegan`, value: `Vegan`, text: `Vegan` },
  ],
};
