export default [
  { key: 'no_select', value: '', text: '-- cancel --' },
  { key: `almay`, value: `almay`, text: `Almay` },
  { key: `alva`, value: `alva`, text: `Alva` },
  { key: `anna_sui`, value: `anna sui`, text: `Anna sui` },
  { key: `annabelle`, value: `annabelle`, text: `Annabelle` },
  { key: `benefit`, value: `benefit`, text: `Benefit` },
  { key: `boosh`, value: `boosh`, text: `Boosh` },
  { key: `burt's_bees`, value: `burt's bees`, text: `Burt's bees` },
  { key: `butter_london`, value: `butter london`, text: `Butter london` },
  { key: `c'est_moi`, value: `c'est moi`, text: `C'est moi` },
  { key: `cargo_cosmetics`, value: `cargo cosmetics`, text: `Cargo cosmetics` },
  { key: `china_glaze`, value: `china glaze`, text: `China glaze` },
  { key: `clinique`, value: `clinique`, text: `Clinique` },
  {
    key: `coastal_classic_creation`,
    value: `coastal classic creation`,
    text: `Coastal classic creation`,
  },
  { key: `colourpop`, value: `colourpop`, text: `Colourpop` },
  { key: `covergirl`, value: `covergirl`, text: `Covergirl` },
  { key: `dalish`, value: `dalish`, text: `Dalish` },
  { key: `deciem`, value: `deciem`, text: `Deciem` },
  { key: `dior`, value: `dior`, text: `Dior` },
  { key: `dr._hauschka`, value: `dr. hauschka`, text: `Dr. hauschka` },
  { key: `e.l.f.`, value: `e.l.f.`, text: `E.l.f.` },
  { key: `essie`, value: `essie`, text: `Essie` },
  { key: `fenty`, value: `fenty`, text: `Fenty` },
  { key: `glossier`, value: `glossier`, text: `Glossier` },
  { key: `green_people`, value: `green people`, text: `Green people` },
  { key: `iman`, value: `iman`, text: `Iman` },
  { key: `l'oreal`, value: `l'oreal`, text: `L'oreal` },
  { key: `lotus_cosmetics_usa`, value: `lotus cosmetics usa`, text: `Lotus cosmetics usa` },
  { key: `maia's_mineral_galaxy`, value: `maia's mineral galaxy`, text: `Maia's mineral galaxy` },
  { key: `marcelle`, value: `marcelle`, text: `Marcelle` },
  { key: `marienatie`, value: `marienatie`, text: `Marienatie` },
  { key: `maybelline`, value: `maybelline`, text: `Maybelline` },
  { key: `milani`, value: `milani`, text: `Milani` },
  { key: `mineral_fusion`, value: `mineral fusion`, text: `Mineral fusion` },
  { key: `misa`, value: `misa`, text: `Misa` },
  { key: `mistura`, value: `mistura`, text: `Mistura` },
  { key: `moov`, value: `moov`, text: `Moov` },
  { key: `nudus`, value: `nudus`, text: `Nudus` },
  { key: `nyx`, value: `nyx`, text: `Nyx` },
  { key: `orly`, value: `orly`, text: `Orly` },
  { key: `pacifica`, value: `pacifica`, text: `Pacifica` },
  { key: `penny_lane_organics`, value: `penny lane organics`, text: `Penny lane organics` },
  { key: `physicians_formula`, value: `physicians formula`, text: `Physicians formula` },
  { key: `piggy_paint`, value: `piggy paint`, text: `Piggy paint` },
  { key: `pure_anada`, value: `pure anada`, text: `Pure anada` },
  { key: `rejuva_minerals`, value: `rejuva minerals`, text: `Rejuva minerals` },
  { key: `revlon`, value: `revlon`, text: `Revlon` },
  {
    key: `sally_b's_skin_yummies`,
    value: `sally b's skin yummies`,
    text: `Sally b's skin yummies`,
  },
  { key: `salon_perfect`, value: `salon perfect`, text: `Salon perfect` },
  { key: `sante`, value: `sante`, text: `Sante` },
  { key: `sinful_colours`, value: `sinful colours`, text: `Sinful colours` },
  { key: `smashbox`, value: `smashbox`, text: `Smashbox` },
  { key: `stila`, value: `stila`, text: `Stila` },
  { key: `suncoat`, value: `suncoat`, text: `Suncoat` },
  { key: `w3llpeople`, value: `w3llpeople`, text: `W3llpeople` },
  { key: `wet_n_wild`, value: `wet n wild`, text: `Wet n wild` },
  { key: `zorah`, value: `zorah`, text: `Zorah` },
  { key: `zorah_biocosmetiques`, value: `zorah biocosmetiques`, text: `Zorah biocosmetiques` },
];
